import os
import pickle
import numpy as np

def main():
    model_path = 'lstm_model.pkl'
    
    print("Model loading check...")
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Could not find trained weights at '{model_path}'. Run train.py first!")
        
    # 1. Load the dictionary payload
    with open(model_path, 'rb') as f:
        payload = pickle.load(f)
        
    # 2. Extract the components cleanly
    model = payload['model']
    train_mean = payload['mean']
    train_std = payload['std']
    print("Model and standardization parameters loaded successfully!")

    # 3. Load the true 173-sample test arrays generated by train.py
    X_val_path = "data/X_val.npy"
    y_val_path = "data/y_val.npy"
    
    if not os.path.exists(X_val_path) or not os.path.exists(y_val_path):
        raise FileNotFoundError("Missing test files in 'data/'. Please rerun train.py to generate them.")
        
    X_val_raw = np.load(X_val_path)  # Shape: (173, 173, 40)
    y_val = np.load(y_val_path)      # Shape: (173,)
    
    print(f"Loaded {X_val_raw.shape[0]} completely unseen validation samples for testing.")
    print(f"X shape: {X_val_raw.shape}")
    print(f"y shape: {y_val.shape}\n")

    # 4. Standardize test data using the EXACT training parameters (No Data Leakage!)
    X_val = (X_val_raw - train_mean) / train_std

    # Class mappings for matching metrics output labels
    classes = ['angry', 'sad', 'happy', 'neutral', 'fear']
    
    # Track metrics for manual summary matrix generation
    y_true_list = []
    y_pred_list = []

    print("Running validation predictions...")
    print("=" * 50)
    
    for i in range(len(X_val)):
        sample = X_val[i]
        actual_class_idx = int(y_val[i])
        
        # 5. Fallback if your class uses .forward() instead of .predict()
        if hasattr(model, 'predict'):
            prob_distribution = model.predict(sample)
        else:
            prob_distribution = model.forward(sample)
            
        # Flatten and compute predictions stable argmax
        prob_distribution = prob_distribution.flatten()
        predicted_class_idx = np.argmax(prob_distribution)
        
        y_true_list.append(actual_class_idx)
        y_pred_list.append(predicted_class_idx)
        
        # Log the first 15 samples visually to monitor alignment
        if i < 15:
            print(f"Validation Sample {i+1}")
            print(f"Predicted: {classes[predicted_class_idx]}")
            print(f"Actual   : {classes[actual_class_idx]}")
            print("-" * 50)

    # 6. Compute Evaluation Performance Matrices from Scratch
    print("\nFINAL VALIDATION METRICS REPORT")
    print("=" * 50)
    print(f"{'Class':<10}{'Precision':<12}{'Recall':<12}{'F1-Score':<12}")
    print("-" * 50)
    
    y_true_arr = np.array(y_true_list)
    y_pred_arr = np.array(y_pred_list)
    
    total_correct = np.sum(y_true_arr == y_pred_arr)
    final_accuracy = (total_correct / len(y_val)) * 100.0
    
    for class_idx, class_name in enumerate(classes):
        # Handle binary slices for multi-class metrics
        tp = np.sum((y_true_arr == class_idx) & (y_pred_arr == class_idx))
        fp = np.sum((y_true_arr != class_idx) & (y_pred_arr == class_idx))
        fn = np.sum((y_true_arr == class_idx) & (y_pred_arr != class_idx))
        
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1_score = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
        
        print(f"{class_name:<10}{precision:<12.4f}{recall:<12.4f}{f1_score:<12.4f}")
        
    print("-" * 50)
    print(f"FINAL VALIDATION ACCURACY: {final_accuracy:.2f}%")
    print("=" * 50)
    print("VALIDATION EVALUATION COMPLETE")

if __name__ == '__main__':
    main()